//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.05 at 04:36:25 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/tsk/services/book", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tsk.services.book;
